version: "3.7"

services: 
  iheros:
    container_name: iheros_api
    build: .
    command: yarn start
    depends_on:
      - db
    links:
      - db  
    ports:
      - "3333:3333"
    networks:
      - iheros  
    volumes: 
      - .:/usr/app
        
  db:
    container_name: iheros_postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "docker"
    networks:
      - iheros

networks:
  iheros:
    driver: bridge
      
  
  